# Generated by Django 3.2.5 on 2021-10-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='following',
            field=models.CharField(default='names', max_length=200),
        ),
    ]
