# Generated by Django 3.2.5 on 2021-10-22 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_userdetails_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='ref',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_ref', to='network.posts'),
        ),
    ]
