# Generated by Django 3.2.5 on 2021-11-05 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='network.posts'),
        ),
    ]
