# Generated by Django 3.2.5 on 2021-11-05 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_likes_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='content',
        ),
        migrations.AddField(
            model_name='likes',
            name='liked_post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='network.posts'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='liked_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
