# Generated by Django 3.2.5 on 2021-11-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_posts_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='liked_by',
            field=models.CharField(default='', max_length=200),
        ),
    ]
